# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"B1259": "B1259.ipynb",
         "analyze_data": "tools.ipynb",
         "simulation": "tools.ipynb",
         "WeightedSource": "tools.ipynb"}

modules = ["b1259.py",
           "tools.py"]

doc_url = "https://tburnett/github.io/light_curves"

git_url = "https://github.com/tburnett/light_curves/tree/master/"

def custom_doc_links(name): return None
