# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MJD": "00_config.ipynb",
         "UTC": "00_config.ipynb",
         "mission_start": "00_config.ipynb",
         "day": "00_config.ipynb",
         "first_data": "00_config.ipynb",
         "Config": "00_config.ipynb",
         "FileConfiguration": "00_config.ipynb",
         "PointSource": "00_config.ipynb",
         "EffectiveArea": "01_effective_area.ipynb",
         "InterpTable": "01_effective_area.ipynb",
         "get_gti": "02_load_gti.ipynb",
         "get_exposure": "03_exposure.ipynb",
         "process_data": "04_data.ipynb",
         "Poisson": "05_poisson.ipynb",
         "PoissonFitter": "05_poisson.ipynb",
         "BinnedWeights": "06_binner.ipynb"}

modules = ["config.py",
           "effective_area.py",
           "load_gti.py",
           "exposure.py",
           "data_management.py",
           "poisson.py",
           "binner.py"]

doc_url = "https://tburnett.github.io/light_curves/"

git_url = "https://github.com/tburnett/light_curves/tree/master/"

def custom_doc_links(name): return None
