# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Cache": "00_config.ipynb",
         "Files": "00_config.ipynb",
         "Config": "00_config.ipynb",
         "MJD": "00_config.ipynb",
         "UTC": "00_config.ipynb",
         "day": "00_config.ipynb",
         "first_data": "00_config.ipynb",
         "PointSource": "00_config.ipynb",
         "EffectiveArea": "01_effective_area.ipynb",
         "InterpTable": "01_effective_area.ipynb",
         "effective_area_plots": "01_effective_area.ipynb",
         "get_gti": "02_gti.ipynb",
         "get_exposure": "03_exposure.ipynb",
         "get_contiguous_exposure": "03_exposure.ipynb",
         "get_photon_data": "04_photon_data.ipynb",
         "check_weights": "05_weights.ipynb",
         "add_weights": "05_weights.ipynb",
         "get_cells": "07_cells.ipynb",
         "partition_cells": "07_cells.ipynb",
         "Poisson": "08_poisson.ipynb",
         "PoissonFitter": "08_poisson.ipynb",
         "Sampler": "09_simulation.ipynb",
         "WeightGenerator": "09_simulation.ipynb",
         "generate_cell": "09_simulation.ipynb",
         "poisson_tolerance": "10_loglike.ipynb",
         "LogLike": "10_loglike.ipynb",
         "GaussianRep": "10_loglike.ipynb",
         "Gaussian2dRep": "10_loglike.ipynb",
         "PoissonRep": "10_loglike.ipynb",
         "PoissonRepTable": "10_loglike.ipynb",
         "fit_cells": "11_lightcurve.ipynb",
         "get_lightcurve": "11_lightcurve.ipynb",
         "flux_plot": "11_lightcurve.ipynb",
         "CountFitness": "14_bayesian.ipynb",
         "LikelihoodFitness": "14_bayesian.ipynb",
         "get_bb_partition": "14_bayesian.ipynb",
         "bb_overplot": "14_bayesian.ipynb"}

modules = ["config.py",
           "effective_area.py",
           "load_gti.py",
           "exposure.py",
           "photon_data.py",
           "weights.py",
           "cells.py",
           "poisson.py",
           "simulation.py",
           "loglike.py",
           "lightcurve.py",
           "bayesian.py"]

doc_url = "https://tburnett.github.io/light_curves/"

git_url = "https://github.com/tburnett/light_curves/tree/master/"

def custom_doc_links(name): return None
