# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/B1259.ipynb (unless otherwise specified).

__all__ = ['B1259']

# Cell
import numpy as np
import matplotlib.pyplot as plt
from wtlike  import Config, PointSource, WtLike, UTC, MJD

from utilities.ipynb_docgen import *

# Cell

class B1259(WtLike):

    tp, period = 55544.694, 1236.7243

    def __init__(self, **kwargs):
        time_bins =kwargs.pop('time_bins', (0,0,1))
        super().__init__('PSR B1259-63', time_bins=time_bins, **kwargs)
        self.applyBB(key='B1259_BB')

    @property
    def mjd_dates(self):
        return [self.tp+n*self.period for n in range(4)]

    def date_info(self):
        return pd.DataFrame([dict(MJD=round(d,3), UTC=UTC(d)) for d in self.mjd_dates ])

    def stacked_plots(self, fignum=3, ylim=(2,200), ts_min=4):

        tp, p =self.tp, self.period
        fig, axx = plt.subplots(4,1, sharex=True, sharey=True, figsize=(12,12), num=fignum)
        plt.subplots_adjust(hspace=0.)
        for i, ax in enumerate(axx.flatten()):
            self.plot_BB( ax=ax, tzero=tp+i*p, xlim=(-60,150), ylim=ylim, ts_min=ts_min,
                     colors=('coral', 'bisque', 'blue'),
                     fmt='o', yscale='log', xlabel='',ylabel='',
                        source_name=self.source.name if i==0 else '')
            ax.text(0.02, 0.05, UTC(tp+i*p)[:4], transform=ax.transAxes)
            ax.axvline(0, color='grey', ls=':')
        axx[-1].set_xlabel('days about periastron', fontsize=20)
        fig.text(0.04, 0.5, 'Relative Flux', va='center', rotation='vertical', fontsize=20)
        fig.width=600
        return fig