# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/Untitled.ipynb (unless otherwise specified).

__all__ = ['B1259Periastron']

# Cell
import numpy as np
import matplotlib.pyplot as plt
from wtlike  import *

from utilities.ipynb_docgen import *

# Cell

class B1259Periastron(WtLike):
    """
    """
    tp, period = 55544.694, 1236.7243

    def __init__(self, **kwargs):
        super().__init__('PSR B1259-63',**kwargs)

    @property
    def mjd_dates(self):
        return [self.tp+n*self.period for n in range(4)]

    def date_info(self):
        return pd.DataFrame([dict(MJD=round(d,3), UTC=UTC(d)) for d in self.mjd_dates ])

    def stacked_plots(self, fignum=3, ylim=(2,200), ts_min=4, p0=0.5):
        dailies = [self.view(tz, tz+125,1) for tz in self.mjd_dates]
        self.bb_views = [daily.bb_view(p0=p0) for daily in dailies]

        fignum=1
        fig, axx = plt.subplots(4,1, sharex=True, sharey=True, figsize=(12,10), num=fignum)
        plt.subplots_adjust(hspace=0, top=0.92)
        for i, (bbv, ax, tzero) in enumerate(zip(self.bb_views, axx.flatten(), self.mjd_dates)):
            bbv.plot(ax=ax, show_flux=True, tzero =tzero, xlim=(0, 125),
                                    source_name=f'{UTC(tzero)[:4]}', ylabel='',
                        legend_loc='upper left' if i==0 else 'none',
                       error_pixsize=0);
        ax.set(xlabel='Days past periastron')
        fig.suptitle('PSR B1259-63 peristron behavior')
        fig.text(0.04, 0.5,'Count flux ($\mathrm{10^{-6}\ cm^{-2}\ s^{-1}}$)', rotation='vertical', va='center' );

        fig.width=600
        return fig